import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "../shared/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: '/images/favicon.png',

};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html data-theme="dark">
      <head></head>
      <body className={inter.className}>
        <Header />
        <main className="w-full mx-auto max-w-screen-2xl">
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
